### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by hades**
This adds support for Python3. All tests run successfully.

### CODE REVIEW

**Comment by joestump** [comment]
@jaitaiwan can you take a look at this? It's related to #158. @hades thanks for the PR! :tada:

**Comment by jaitaiwan** [comment]
@joestump added to the list. I have a feeling that my PR doesn't use the futures lib... but I don't think any others do either. Will continue the chat in #158.

**Comment by jaitaiwan** [comment]
This one fails to work in Pyk2 so I think we may drop it https://travis-ci.org/CentricWebEstate/python-oauth2/jobs/75874253

Thoughts @rickhanlonii @joestump?

**Comment by rickhanlonii** [comment]
Yeah, there are other pk3 wips that are farther along at this point. Thanks for the contribution @hades!

**Pull request closed without merging**
