### PR TITLE
Py3k compatibility

### PR DESCRIPTION
**Pull request by tseaver**
All tests pass under tox against Python 2.6, 2.7, 3.2, and 3.3.

### CODE REVIEW

**Comment by delewis1987** [comment]
+1

**Comment by LynnCo** [comment]
+1

**Comment by joestump** [comment]
See #158 as well. cc @jaitaiwan

**Comment by joestump** [comment]
@tseaver You interested in becoming a collaborator on this? Second solid PR I've seen from you so far. :+1:

**Comment by jaitaiwan** [comment]
@joestump which PR should we use?

**Comment by jaitaiwan** [comment]
This one has collisions...

**Comment by joestump** [comment]
@jaitaiwan Up to you. I think yours is newer and had more eyes on it, which always gets my vote. I mainly wanted to ask if @tseaver was interested in helping out. :laughing:

**Comment by tseaver** [comment]
I had just about enough mental swap space left to fix #141.  I'm afraid that updating this one requires swapping way more of the code back into my head than I have available for the foreseeable future.

**Comment by joestump** [comment]
@tseaver haha, totally understand. Thanks so much for your help with #141 and your PRs. :tada:

**Comment by hayd** [comment]
There's a subtley here IMO, should all the things return as utf8 encoded bytes (as is the idea in this PR) or unicode (as most of stdlib does).

In a trial merge I changed it to unicode and basically the only fail was [test_to_url_nonascii](https://github.com/joestump/python-oauth2/blob/b909b4808de79dacd6472c6bbb9d3fc02931e128/tests/test_oauth.py#L381). Thoughts?

**Comment by rickhanlonii** [comment]
@jaitaiwan @joestump I spent some time today trying to fix the tests on #176 and found that we're going to need to make rather extensive changes if we want to use that PR (i.e. in Python 3 `urlparse.urlsplit` returns bytes so string checks fail). Those changes seem to already be contained in this PR.

I'm thinking we get this merged into `feat-python-3` so we can all work on getting python 3 compatibility working with this as a base.

**Comment by rickhanlonii** [comment]
I attempted a master on merge [here](https://github.com/rickhanlonii/python-oauth2/tree/py3-redux).

All tests pass for 2.6 and 2.7. There are a only 2 of the new tests failing in python 3:

```
Failure
Traceback (most recent call last):
  File "/Users/euler/dev/python-oauth2/py3.4/lib/python3.4/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/euler/dev/python-oauth2/tests/test_oauth.py", line 908, in test_request_nonutf8_bytes
    self.assertRaises(TypeError, oauth.Request, method="GET", url=url, parameters=params)
AssertionError: TypeError not raised by Request


Failure
Expected :'http[38 chars]asdf&foo=baz&uni_utf8=%C2%AE&bar=foo&multi=%5B[81 chars]3%98'
Actual   :'http[38 chars]asdf&uni_unicode_2=%C3%A5%C3%85%C3%B8%C3%98&un[79 chars]=baz'
 <Click to see difference>

Traceback (most recent call last):
  File "/Users/euler/dev/python-oauth2/tests/test_oauth.py", line 478, in test_to_url_works_with_non_ascii_parameters
    'http://example.com?oauth_consumer=asdfasdfasdf&'
AssertionError: 'http[38 chars]asdf&foo=baz&uni_utf8=%C2%AE&bar=foo&multi=%5B[81 chars]3%98' != 'http[38 chars]asdf&uni_unicode_2=%C3%A5%C3%85%C3%B8%C3%98&un[79 chars]=baz'
- http://example.com?oauth_consumer=asdfasdfasdf&foo=baz&uni_utf8=%C2%AE&bar=foo&multi=%5Bb%27FOO%27%2C+b%27BAR%27%5D&uni_unicode=%C2%AE&uni_unicode_2=%C3%A5%C3%85%C3%B8%C3%98
+ http://example.com?oauth_consumer=asdfasdfasdf&uni_unicode_2=%C3%A5%C3%85%C3%B8%C3%98&uni_utf8=%C2%AE&multi=%5B%27FOO%27%2C+%27BAR%27%5D&uni_unicode=%C2%AE&bar=foo&foo=baz
```

**Comment by jaitaiwan** [comment]
Getting closer!

**Comment by hayd** [comment]
for the latter test: %5Bb%27FOO%27%2C+b%27BAR%27%5D has the b in b'..' which I don't think it should. I think it's easiest just to split i on `?` then `&` (and test the set).

Thoughts on the bytes vs unicode issue?

**Comment by jaitaiwan** [comment]
I personally opt for unicode, I feel like its the way of the future...

**Comment by hayd** [comment]
In which case (I have a merge) which fails only: test_to_url_nonascii (py2.6+ and py3) and test_to_url_works_with_non_ascii_parameters (py2). These are kinda tricky since the unicode arguments aren't valid unicode (so it feels like this is expected).

**Comment by jaitaiwan** [comment]
Hey @hayd do you reckon you'd be interested in becoming a contributor? Seems like you're super keen to help this project along! cc @joestump

**Comment by rickhanlonii** [comment]
+1

**Comment by jaitaiwan** [comment]
cc @joestump: this is the PR we're looking at for py3k over my stuff.

**Comment by rickhanlonii** [comment]
@jaitaiwan @joestump should this be against `develop` or a feature branch?

**Comment by jaitaiwan** [comment]
It's a big change so I'd say feature branch

**Comment by rickhanlonii** [comment]
@tseaver can you re-open against branch `feat-python-3`?

**Comment by tseaver** [comment]
@rickhanlonii I'm happy to have somebody rebase / merge my work to such a branch, but I'm afraid I don't have capacity for that effort at this point.

**Comment by rickhanlonii** [comment]
No sweat. @hayd and I both took a stab at it already, just wanted to give you the opportunity first.

**Pull request closed without merging**
