### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by mkaziz**
I was just implementing oauth for my twitter/django application, and while the readme was really helpful, some commands were out of date (for example, the twitter API url's have been updated, parameters have been changed, etc). I've updated these in the documentation.

### CODE REVIEW

**Comment by joestump** [comment]
Closed the wrong PR. Sorry about that. Some of this is fixed.

**Comment by mkaziz** [comment]
Khalid Aziz
Computer Science
McCormick School of Engineering and Applied Science
Northwestern University, Class of 2013
Phone: 832-539-3947

**Comment by jaitaiwan** [comment]
@joestump for review or needs work?

**Comment by joestump** [comment]
I think we need to revisit the README's example and update it for Django 3, etc. I'd close this out for now I think.

**Pull request closed without merging**
