### PR TITLE
Python 3 Compatibility

### PR DESCRIPTION
**Pull request by jaitaiwan**
I'm not sure these changes ensure FULL compatibility but I believe running this should have no errors in 3 now. Also not sure if this breaks backwards compatibility...

### CODE REVIEW

**Comment by hayd** [comment]
3.3 and 3.4 should be added to the travis matrix, potentially as allowable failures if they're failing. But currently this branch is failing. :s

**Comment by jaitaiwan** [comment]
Yeh I noticed that. About to push changes which will make travis build for 3.4 and 3.3

**Comment by jaitaiwan** [comment]
Bit of work to do before this can be accepted. Since I ran the tests on the original PR looks like a bunch of things have changed.

**Comment by hayd** [comment]
I have a small commit you can cherry pick to fix this (I can make a PR as I forgot to turn on travis, but it passes locally).
https://github.com/hayd/python-oauth2/commit/2cef249160f3060be22a65f67b809fad27556415

all tests pass on python2 (2.6 and 2.7) and python 3.... except one (which fails in master too).

```
======================================================================
FAIL: test_get_normalized_parameters_multiple (tests.test_oauth.TestRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andy/proj/python-oauth2/tests/test_oauth.py", line 638, in test_get_normalized_parameters_multiple
    self.assertEquals(expected, res)
AssertionError: 'oauth_consumer_key=mykey&oauth_nonce=79815175&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1295397962&oauth_version=1.0&offset=10&tag=one&tag=two' != 'oauth_consumer_key=mykey&oauth_nonce=79815175&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1295397962&oauth_version=1.0&offset=10&tag=%5B%27one%27%2C%20%27two%27%5D'
```

**Comment by movinj** [comment]
Hi guys.. I'm looking to use oauth2 with Python 3.4
Have you had any luck with fixing the compatibility?

**Comment by jaitaiwan** [comment]
Projects only been alive for a couple days after being dead for about 4 years so we're getting there! Definitely keep an eye on this PR or even feel free to contribute...

**Comment by movinj** [comment]
Thanks @jaitaiwan. I'm a rookie so may not be able to help yet.. but looking out for you guys to pull this through :+1:

**Comment by rickhanlonii** [comment]
@jaitaiwan should we move this to a feature branch so others can help out?

**Comment by rickhanlonii** [comment]
I created branch `feat-python-3`.

**Comment by hayd** [comment]
I think the best bet is to get #142 working, I had a little go (we're all re-inventing the wheel otherwise).

**Comment by jaitaiwan** [comment]
Yup I'm closing this one out in favour of #142

**Pull request closed without merging**
