### PR TITLE
Lowercase scheme and authority per specification.

### LINKED ISSUE #29: URLs are not normalised properly
According to http://oauth.net/core/1.0a/#rfc.section.9.1.2, URLs must be normalised before using for signatures.

To fix it, it seems enough to change http://github.com/simplegeo/python-oauth2/blob/master/oauth2/__init__.py#LID292 to read:

self.normalized_url = urlparse.urlunparse((scheme.lower(), netloc.lower(), path, None, None, None))

Otherwise it will break when using URLs like HTTP://Example.com/foo/bar

### PR DESCRIPTION
**Pull request by joestump**
Closes #29. More robustly follows [URL normalization per the specification](http://oauth.net/core/1.0a/#rfc.section.9.1.2) now. See #133 for additional and related discussion.

### CODE REVIEW

**Comment by jaitaiwan** [comment]
LGTM for 2.0. @rickhanlonii @joestump I'm a fan of using the git flow workflow... would you both be keen to follow that? Means that all future PR's should be against either a develop branch or a specific release branch.

**Comment by rickhanlonii** [comment]
+1 big fan of git flow as well.

**Comment by jaitaiwan** [comment]
cool 3/3 for git flow. @joestump can you please close this and do a request with these changes against develop?

**Comment by joestump** [comment]
Closed out in favor of #183.

**Pull request closed without merging**
