### PR TITLE
Normalizing parameters duplicated in URL query string and POST parameters

### PR DESCRIPTION
**Pull request by arthurian**
This PR modifies the merging of POST parameters with URL query parameters in ```get_normalized_parameters()``` so that duplicate parameters (same key/value) are not duplicated in the normalized base string. 

I could not find any guidance on this issue from [RFC 5849](https://tools.ietf.org/html/rfc5849#section-3.4.1.3.2). Thoughts?

Note: per @jaitaiwan's request, I've closed https://github.com/joestump/python-oauth2/pull/195 and reopened it here so that it's compared to *develop* instead of *master*.

### CODE REVIEW

**Comment by jaitaiwan** [comment]
Thanks @arthurian :)

The issue with duplicated parameters is that it's up to the receiving server to determine how to deal with the url. We discussed a similar case in regards to arrays in urls. In which case the current implementation would end up looking like an array to some web servers, potentially breaking it.

So from my perspective this pull request is definitely needed.

How I personally think this should be implemented is similar to the way PHP populates it's `$_REQUEST` variable which contains variables from session, cookie, post and get. POST vars should override GET vars.

@joestump @rickhanlonii what are your thoughts?

**Comment by GuillaumeDerval** [comment]
Any news on this? Would be nice if merged :-)

**Comment by jaitaiwan** [comment]
I've confirmed this merge and we'll see how it goes!

**Comment by nikolas** [comment]
Can you publish a new release on pypi that includes this?

**Pull request merged**
