### PR TITLE
Restore 100% unit test coverage

### PR DESCRIPTION
**Pull request by tseaver**
Document the supported versions using Trove classifiers.

Test against all supported Python versions (2.5 - 2.7) using tox.

Test coverage separately (using 'tox -e cover').

Add tests to restore 100% coverage.

### CODE REVIEW

**Comment by joestump** [comment]
cc @jaitaiwan I think we should fold this into our CI work. Not sure if `tox` is needed for that work, but I'd like to get the test coverage and other fixes in.

**Comment by jaitaiwan** [comment]
I'd like to see this folded into the CI stuff although Travis already provides multiple CI python versions... unless tox does this differently somehow?

**Comment by tseaver** [comment]
FWIW, the key feature of `tox` is that it allows the developer to run the tests locally before pusing (assuming she has the appropriate Python versions available).  Travis can then be used to drive tox. For instance, see:

- https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/.travis.yml
- https://github.com/zopefoundation/zope.component/blob/master/.travis.yml

**Comment by tseaver** [comment]
Merged w/ master and fixed test failures due to hash randomization.

**Comment by joestump** [comment]
@jaitaiwan the main thing you get with `tox`, as @tseaver mentioned, is being able to run tests against multiple versions of Python locally. Travis does this on PR. I propose we split this into two PRs, get the test coverage merged in, and then move the `tox` discussion to a 2.0 thread.

**Comment by jaitaiwan** [comment]
:+1:

**Comment by jaitaiwan** [comment]
@tseaver reckon you could open a new PR against master instead?

**Comment by tseaver** [comment]
@joestump I merged with master yesterday, and added a couple of test fixes.

**Comment by jaitaiwan** [comment]
Ugh sorry @tseaver I meant develop instead of master.

**Pull request closed without merging**
