### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### joestump/python-oauth2 now has a Chat Room on Gitter

@rickhanlonii has just created a chat room. You can visit it here: [https://gitter.im/joestump/python-oauth2](https://gitter.im/joestump/python-oauth2?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/joestump/python-oauth2?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by rickhanlonii** [comment]
@joestump @jaitaiwan are you interested in creating a Gitter room to discuss things a little more realtime?

**Comment by joestump** [comment]
@rickhanlonii I'm down.

**Comment by jaitaiwan** [comment]
@rickhanlonii same here. I'm also keen on supporting via IRC. I idle there alot.

**Comment by rickhanlonii** [comment]
Happy to idle on IRC too!

**Comment by jaitaiwan** [comment]
@joestump @rickhanlonii do you want this in RC1?

**Comment by rickhanlonii** [comment]
Let's leave it out for RC1.

**Comment by jaitaiwan** [comment]
:+1:

**Pull request merged**
