### PR TITLE
Normalize the url when it contains default HTTP/HTTPS ports

### PR DESCRIPTION
**Pull request by frankdu**
Summary:
Remove the default ports part, when the url has default HTTP/HTTPS
ports (i.e. 80/443)

### CODE REVIEW

**Comment by joestump** [comment]
@frankdu Thanks for all of the PRs. @jaitaiwan and I are gonna go through them. What's the purpose of this PR? Were you getting errors when you passed the port along to some providers?

**Comment by jaitaiwan** [comment]
If we can get Travis to run tests over this again, it might be fine as is. I don't see a reason why this can't be included...

**Comment by frankdu** [comment]
Yes, it was for solving real problem, because client/server may use different libraries. The URL normalization wasn't same which caused error.

**Comment by joestump** [comment]
@frankdu & @jaitaiwan it looks like this work [is already in master](https://github.com/joestump/python-oauth2/blob/master/oauth2/__init__.py#L359-L368). It appears @mmalone added it in 552cacc0ccc37891ad3d09e10911ffd0c6e3ea62. I'm not sure there's test coverage for this issue though.

**Comment by joestump** [comment]
Just checked and it's covered by tests. I'm going to close this out as it appears to have already snuck in elsewhere. @frankdu can you test your code against the latest master to ensure your issue is entirely resolved? Reopen if it's not.

**Pull request closed without merging**
